apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dsa
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/dsa
    repoURL: 'https://github.com/Magisterka-Maurycy/GitOps.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
    automated:
      prune: false
      selfHeal: false
