kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dsa
  name: namespace-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: dsa
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""